FROM --platform=amd64 amd64/ubuntu

# Install wget
RUN apt-get update && apt-get install wget -y

# Install yq for manipulating YAML files
RUN sh -c "wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq"

# Install Stack
RUN sh -c "wget -qO- https://get.haskellstack.org/ | sh"

CMD ["bash"]
