FROM vladimirlogachev/ubuntu-haskell-stack-amd64

WORKDIR /app

# Create temporary Stack project
RUN stack new temp
WORKDIR /app/temp

# escape=`
RUN sh -c "cat stack.yaml | yq e '.resolver.url = \"https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/27.yaml\"' - >> stack.yaml.tmp"
RUN mv stack.yaml.tmp stack.yaml

# Project build command forces Stack to install GHC and base
RUN stack build

WORKDIR /app
RUN rm -rf temp

CMD ["bash"]
